{
  "openapi": "3.0.0",
  "info": {
    "title": "Litmus Authentication Server",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "localhost:3000"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/status": {
      "get": {
        "tags": [
          "default"
        ],
        "summary": "Status",
        "description": "Helps check status of the Server",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 23 Jul 2021 11:35:59 GMT"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "15"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "up"
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Login",
        "description": "Login into Auth Server",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "username": "admin",
                  "password": "admin"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 23 Jul 2021 11:40:23 GMT"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "308"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "access_token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjcxMjY4MjMsInJvbGUiOiJhZG1pbiIsInVpZCI6ImY4MDM2YzUxLTBkNzktNGNkNy1hN2QwLTQ1ZGNhZGI4MGVlYiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.zNIMwocHgmguwtGFupV54UfcfwEdaRO1_xB2ilalqn0fp-JE0ujkHT3gDyepnEGSRm2j1eTopPgtvyRVPb7gGA",
                  "expires_in": 86400,
                  "type": "Bearer"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 23 Jul 2021 11:37:19 GMT"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "117"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "error": "unauthorized",
                  "error_description": "The user does not have requested authorization to access this resource"
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": [
          "default"
        ],
        "summary": "Get all Users",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 23 Jul 2021 11:42:41 GMT"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "108"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "_id": "f8036c51-0d79-4cd7-a7d0-45dcadb80eeb",
                    "username": "admin",
                    "role": "admin",
                    "created_at": "1627040098"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/update/password": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Update Password",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "username": "admin",
                  "old_password": "admin",
                  "new_password": "litmus"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 23 Jul 2021 11:44:06 GMT"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "37"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "password has been reset"
                }
              }
            }
          }
        }
      }
    },
    "/create": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Create User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "username": "test1",
                  "password": "test1",
                  "role": "admin",
                  "email": "test1@litmus.com",
                  "name": "Test Account"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 23 Jul 2021 11:46:39 GMT"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "155"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "_id": "5873815a-1535-4b1c-8766-2fe53c726276",
                  "username": "test1",
                  "email": "test1@litmus.com",
                  "name": "Test Account",
                  "role": "admin",
                  "created_at": "1627040799"
                }
              }
            }
          }
        }
      }
    },
    "/reset/password": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Reset Password",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "username": "test1",
                  "new_password": "test2"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 23 Jul 2021 11:47:28 GMT"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "50"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "password has been reset successfully"
                }
              }
            }
          }
        }
      }
    },
    "/update/details": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Update User Details",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Administrator",
                  "email": "admin@litmus.com",
                  "role": "admin",
                  "username": "admin"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 23 Jul 2021 11:50:31 GMT"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "130"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "_id": "f8036c51-0d79-4cd7-a7d0-45dcadb80eeb",
                  "username": "admin",
                  "email": "admin@litmus.com",
                  "name": "Administrator",
                  "role": "admin"
                }
              }
            }
          }
        }
      }
    },
    "/updatestate": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Update User State",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "": ""
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}
